// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGiTbclBaFR20vjuLhKYixrhMOhWSoImU',
    appId: '1:285530457854:web:120d54d63e2ecba866c7af',
    messagingSenderId: '285530457854',
    projectId: 'chatapp-f0da3',
    authDomain: 'chatapp-f0da3.firebaseapp.com',
    storageBucket: 'chatapp-f0da3.firebasestorage.app',
    measurementId: 'G-4KXJ7EFT5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZCvCdUX2xcnDAzSlL983Xk0zLBNIJDII',
    appId: '1:285530457854:android:2c9ce9f8699950fd66c7af',
    messagingSenderId: '285530457854',
    projectId: 'chatapp-f0da3',
    storageBucket: 'chatapp-f0da3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6AugBGwijGtWpjP38Cii_mF95gr0Y-g',
    appId: '1:285530457854:ios:bbe2103d0319e81d66c7af',
    messagingSenderId: '285530457854',
    projectId: 'chatapp-f0da3',
    storageBucket: 'chatapp-f0da3.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6AugBGwijGtWpjP38Cii_mF95gr0Y-g',
    appId: '1:285530457854:ios:bbe2103d0319e81d66c7af',
    messagingSenderId: '285530457854',
    projectId: 'chatapp-f0da3',
    storageBucket: 'chatapp-f0da3.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGiTbclBaFR20vjuLhKYixrhMOhWSoImU',
    appId: '1:285530457854:web:0548ec46e90ced1266c7af',
    messagingSenderId: '285530457854',
    projectId: 'chatapp-f0da3',
    authDomain: 'chatapp-f0da3.firebaseapp.com',
    storageBucket: 'chatapp-f0da3.firebasestorage.app',
    measurementId: 'G-4R5ZG4XS6B',
  );
}